// <auto-generated />
using System;
using Interventions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Interventions.Migrations
{
    [DbContext(typeof(InterventionsContext))]
    [Migration("20190417134248_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Interventions.Data.Entities.DeclarerProbleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("courriel")
                        .HasMaxLength(100);

                    b.Property<string>("courrielConfirmation")
                        .HasMaxLength(100);

                    b.Property<DateTime>("dateProbleme");

                    b.Property<string>("descriptionProbleme")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("noTypeProbleme");

                    b.Property<string>("noUnite")
                        .HasMaxLength(20);

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("notification")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("telephone")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("CategoriesProbleme");
                });

            modelBuilder.Entity("Interventions.Data.Entities.TypeProbleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descriptionTypeProbleme")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Probleme");
                });
#pragma warning restore 612, 618
        }
    }
}
